---
title: "Exploratory Data Analysis"
format: html
editor: visual
---

# Elements of structured data

Data types:

-   Numeric: data that are expressed on a numeric scale

    -   Continuous: data that can take on any value in an interval (synonyms: interval, float, numeric)

    -   Discrete: data than can take on only integer values, such as counts (synonyms: integer, count)

-   Categorical: data that can take on only a specific set of values representing a set of possible categories (synonyms: enums, enumerated, factors, nominal)

    -   Binary: a special case of categorical data with just two categories of values, e.g. 0/1, true/false (synonyms: dichotomous, logical, indicator, boolean)

    -   Ordinal: categorical data that has an explicit ordering (synonym: ordered factor)

# Rectangular data

-   Data frame: rectangular data (like a spreadsheet) is the basic data structure for statistical and machine learning models

-   Feature: a column within a table is commonly referred to as a *feature* (synonyms: attribute, input, predictor, variable)

-   Outcome: many data science projects involve predicting an *outcome* - often a yes/no outcome. The *features* are sometimes used to predict the *outcome* in an experiment or a study (synonyms: dependent variable, response, target, output)

-   Records: a row within a table is commonly referred to as a *record* (synonyms: case, example, instance, observation, pattern, sample)

# Estimates of location
